### ISSUE TITLE
Not usable in UITableView

### ISSUE THREAD

**Issue by kamil-tomaszewski** [STAR-ZERO/STZPullToRefresh#1]
You're component, although great, is not working when the number of rows doesn't exceed the space on screen. Hence the scroll behavior isn't achievable and the delegate isn't called. Set the number of rows in your example to let's say 5 and you will observe the described behavior.

**Comment by STAR-ZERO** [comment]
See https://github.com/STAR-ZERO/STZPullToRefresh/blob/master/Example/Example/ViewController.m#L50

I do not think is a good process, but it is working.

Please PullRequest if there is a good way.

**Comment by kamil-tomaszewski** [comment]
I think I won't come up with anything better than this, well at least without changing how the component works and the mechanism it uses.
